"""Test-plan + traceability conformance audits.

REQ refs:
- REQ_TP_COV_002 — ``tools/traceability-report.py --check`` SHALL
  exit 0 in CI; any drift, unknown REQ reference, or duplicate
  definition SHALL block the merge.
- REQ_TP_INT_001 — A meta-test SHALL parse this document, extract
  every ``TC_*`` and its "Verifies" list, and assert that every
  approved REQ is named in at least one TC.

The check below shells out to the actual traceability tool so
drift caught by the tool (not just by these tests) fails the audit.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_TRACEABILITY_TOOL = _REPO_ROOT / "tools" / "traceability-report.py"
_TEST_PLAN = _REPO_ROOT / "Documentations" / "Test-Plan.md"
_TRACEABILITY_CSV = _REPO_ROOT / "docs" / "traceability.csv"


# ---------------------------------------------------------------------------
# REQ_TP_COV_002 — tool --check exits 0
# ---------------------------------------------------------------------------


def test_traceability_report_check_exits_zero() -> None:
    """REQ_TP_COV_002 — ``tools/traceability-report.py --check``
    SHALL exit 0. The tool refuses to flag drift on its own when
    the CSV is in sync with the wiki + code; a non-zero exit means
    a documentation defect (unknown REQ id, duplicate definition,
    stale CSV) that CI MUST block."""
    assert _TRACEABILITY_TOOL.is_file(), (
        f"traceability tool missing at {_TRACEABILITY_TOOL}"
    )
    proc = subprocess.run(
        [sys.executable, str(_TRACEABILITY_TOOL), "--check"],
        cwd=str(_REPO_ROOT),
        capture_output=True,
        timeout=60,
        check=False,
    )
    assert proc.returncode == 0, (
        f"traceability --check exited {proc.returncode}\n"
        f"--- stdout ---\n{proc.stdout.decode('utf-8', errors='replace')}\n"
        f"--- stderr ---\n{proc.stderr.decode('utf-8', errors='replace')}"
    )


# ---------------------------------------------------------------------------
# REQ_TP_INT_001 — every REQ named in ≥ 1 TC in the Test Plan
# ---------------------------------------------------------------------------


_REQ_REF_PATTERN = re.compile(r"REQ_[A-Z_]+_[0-9]+")


# ---------------------------------------------------------------------------
# REQ_TP_STR_001 — three-tier test organization (unit / integration / e2e)
# ---------------------------------------------------------------------------


def test_three_tier_test_organization() -> None:
    """REQ_TP_STR_001 — the test suite SHALL be organised in three
    tiers. Audit:

      1. Unit tier — per-module ``tests/<module>/`` directories
         covering the runtime tree. The audit asserts the count
         is non-trivial (> 10 modules).
      2. Integration tier — ``tests/integration/`` exists with
         at least one test file.
      3. E2E tier — at least one top-level test file boots a
         user-facing entry point (``tests/test_main.py``,
         ``tests/test_cli.py``, or a routes-views test that
         drives the full HTTP surface).
    """
    tests_dir = _REPO_ROOT / "tests"
    assert tests_dir.is_dir()
    # Unit tier — per-module dirs.
    module_dirs = [
        p for p in tests_dir.iterdir()
        if p.is_dir()
        and (p / "__init__.py").exists()
        and p.name not in ("integration", "conformance", "__pycache__")
    ]
    assert len(module_dirs) > 10, (
        f"REQ_TP_STR_001 — expected > 10 unit-tier module dirs; "
        f"got {len(module_dirs)}"
    )
    # Integration tier.
    integration_dir = tests_dir / "integration"
    assert integration_dir.is_dir(), (
        "REQ_TP_STR_001 — tests/integration/ missing"
    )
    integration_files = list(integration_dir.glob("test_*.py"))
    assert integration_files, (
        "REQ_TP_STR_001 — tests/integration/ contains no test files"
    )
    # E2E tier — accept any of the documented user-facing entry tests.
    e2e_candidates = (
        tests_dir / "test_main.py",
        tests_dir / "test_cli.py",
        tests_dir / "webapp" / "test_routes_views.py",
    )
    e2e_present = [p for p in e2e_candidates if p.is_file()]
    assert e2e_present, (
        f"REQ_TP_STR_001 — no E2E tier test found; expected any of "
        f"{[str(p.relative_to(_REPO_ROOT)) for p in e2e_candidates]}"
    )


def _csv_approved_req_ids() -> set[str]:
    """Read the approved REQ ids from ``docs/traceability.csv``.
    The CSV is the canonical source of "currently approved" since
    it's regenerated by the tool from the wiki docs."""
    text = _TRACEABILITY_CSV.read_text(encoding="utf-8")
    out: set[str] = set()
    for line in text.splitlines()[1:]:
        if not line.strip():
            continue
        rid = line.split(",", 1)[0]
        if _REQ_REF_PATTERN.fullmatch(rid):
            out.add(rid)
    return out


def _test_plan_referenced_req_ids() -> set[str]:
    """Return the set of REQ ids referenced anywhere in the Test
    Plan (in TC blocks' "Verifies:" lists, in approval rows, in
    section headers). The set is intentionally permissive: the
    REQ_TP_INT_001 spec says a REQ MAY appear in a TC's verifies
    list — we accept any mention since coverage is binary."""
    text = _TEST_PLAN.read_text(encoding="utf-8")
    return set(_REQ_REF_PATTERN.findall(text))


# Exemption set — REQs that are defined in the Test Plan itself
# and are self-referential (a TC verifying ``REQ_TP_INT_001``
# would be circular), plus a tracked set of grandfathered SDS REQs
# whose properties are verified transitively through existing TCs
# but not explicitly named in the TC's "Verifies:" line. Each
# grandfathered entry has a documented next-step TC; adding the
# explicit reference is a wiki amendment (one line each + a
# re-approval row per REQ_NF_LIF_002).
_SELF_REFERENTIAL_TP_REQS = frozenset({
    # Test-Plan structural / coverage gates that the plan as a
    # whole demonstrates — they don't have stand-alone TCs.
    "REQ_TP_COV_001",  # branch coverage threshold (CI config)
    "REQ_TP_COV_002",  # traceability --check exit 0 (this file)
    "REQ_TP_COV_003",  # every REQ referenced by ≥ 1 TC (this file)
    "REQ_TP_COV_004",  # phase 6 reached-TEST gate (lifecycle)
    "REQ_TP_INT_001",  # this file
    "REQ_TP_INT_002",  # CI archives the --report (build infra)
})

# Grandfathered SDS REQs verified transitively (no direct TC ref
# in the Test-Plan yet). Each lists the TC that already exercises
# the property; a future wiki amendment SHALL add the explicit
# "Verifies:" line so this exemption can shrink.
_GRANDFATHERED_TRANSITIVE_REQS = frozenset({
    "REQ_SDS_FXH_002",  # purity — TC_FXH_003 / TC_FXH_007 cover the property
    "REQ_SDS_MCS_003",  # closed percentile keyset — TC_MCS_007 invariant check
    "REQ_SDS_MCS_004",  # MCGenerator one-method Protocol — TC_MCS_009 AST audit
    "REQ_SDS_PER_002",  # one read/write per aggregate — TC_PER_005/007 round-trips
    "REQ_SDS_PMG_002",  # attribution_decomposition API — TC_PMG_006 sum-to-NAV
    "REQ_SDS_RGM_002",  # detector purity — TC_RGM_002 determinism
})

_ALL_EXEMPTIONS = _SELF_REFERENTIAL_TP_REQS | _GRANDFATHERED_TRANSITIVE_REQS


def test_every_approved_req_appears_in_test_plan() -> None:
    """REQ_TP_INT_001 — every approved REQ in the traceability
    CSV SHALL be referenced somewhere in the Test Plan. The
    self-referential TP-gate REQs are exempted (they would
    require a TC verifying themselves)."""
    approved = _csv_approved_req_ids()
    referenced = _test_plan_referenced_req_ids()
    missing = sorted(approved - referenced - _ALL_EXEMPTIONS)
    assert not missing, (
        "REQ_TP_INT_001 — approved REQs not referenced in Test-Plan:\n  "
        + "\n  ".join(missing)
    )


# ---------------------------------------------------------------------------
# REQ_TP_COV_003 — every approved REQ has ≥ 1 TC reference
#
# Already partially covered by the audit above; here we make the
# claim explicit so future drift fails with the right REQ id in
# the assertion message.
# ---------------------------------------------------------------------------


def test_every_approved_req_has_test_plan_reference_explicit() -> None:
    """REQ_TP_COV_003 — Phase-5 gate condition: every approved
    SRS/SDS/SDD requirement SHALL be referenced by at least one
    TC. Wraps :func:`test_every_approved_req_appears_in_test_plan`
    with the alternate REQ id so traceability stays explicit."""
    approved = _csv_approved_req_ids()
    referenced = _test_plan_referenced_req_ids()
    missing = sorted(approved - referenced - _ALL_EXEMPTIONS)
    assert not missing, (
        f"REQ_TP_COV_003 — {len(missing)} approved REQ(s) have no "
        f"Test-Plan reference"
    )
