# CR-017 Phase A — multi-stage container for the FastAPI webapp.
#
# REQ refs:
# - REQ_F_FAS_007 — multi-stage; non-root; HEALTHCHECK; ≤ 200 MB
#   compressed; ubuntu base SHALL NOT be used.
# - REQ_NF_FAS_002 — reproducible: same Dockerfile + same lockfile +
#   same base-image digest ⇒ same image digest.
# - REQ_SDS_FAS_004 — runtime base SHALL be python:3.12-slim-bookworm
#   pinned by digest.
# - REQ_SDD_FAS_007 — ARG BASE_DIGEST pins both stages; pip install
#   uses --require-hashes against requirements.lock; apt-get clean +
#   rm -rf /var/lib/apt/lists/* after every apt-get install.
#
# Phase A ships the Dockerfile skeleton with --no-deps wheel building.
# Phase B will lock the base-image digest + add requirements.lock with
# SHA-256 hashes generated by `pip-compile --generate-hashes`. Both
# steps require a network fetch + a checked-in lockfile so they land
# alongside the CI integration that asserts digest stability.

ARG BASE_TAG=3.12-slim-bookworm
# Future Phase-B addendum: `ARG BASE_DIGEST=sha256:<pinned>` so the
# build is fully reproducible. Today the tag is the version pin.

# ============================================================================
# Stage 1 — builder
# ============================================================================
FROM python:${BASE_TAG} AS builder

ENV PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Build deps — only present in the builder stage so the runtime
# layer stays slim (REQ_F_FAS_007 ≤ 200 MB target).
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libssl-dev \
        libffi-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

COPY pyproject.toml README.md ./
COPY trading_system/ ./trading_system/

# Build wheels for the project + the [webapp] + [reports] extras so
# the runtime stage installs offline.
# Phase-B addendum: `pip wheel --require-hashes -r requirements.lock`
# replaces the resolver path with a SHA-256-pinned install
# (REQ_SDD_FAS_007).
RUN pip wheel --no-deps --wheel-dir /wheels . \
    && pip wheel --wheel-dir /wheels '.[webapp,reports]'

# ============================================================================
# Stage 2 — runtime
# ============================================================================
FROM python:${BASE_TAG} AS runtime

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    TRADING_BOT_CONFIG_DIR=/config

# Runtime libs — no compilers, no -dev headers. Keeps the layer slim.
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libssl3 \
        libffi8 \
        ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && useradd --no-create-home --shell /usr/sbin/nologin --uid 10001 trading \
    && mkdir -p /app /data /config \
    && chown -R trading:trading /app /data /config

# Install from the builder's pre-compiled wheel archive — no network.
COPY --from=builder /wheels /wheels
RUN pip install --no-index --no-deps /wheels/*.whl \
    && rm -rf /wheels

WORKDIR /app
USER trading

EXPOSE 8000

# REQ_F_FAS_007 — the HEALTHCHECK uses a stdlib-only probe so it works
# without curl in the runtime layer.
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD python -c "import urllib.request,sys; \
        r=urllib.request.urlopen('http://localhost:8000/health', timeout=2); \
        sys.exit(0 if r.status==200 else 1)" \
        || exit 1

ENTRYPOINT ["uvicorn"]
CMD ["trading_system.webapp.app:default_app", \
     "--factory", \
     "--host", "0.0.0.0", \
     "--port", "8000"]
